Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.display import SVG, display

G_pydot = G.to_dot(backend="pydot")
display(SVG(G_pydot.create_svg()))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[7], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m SVG, display
[0;32m----> 3[0m G_pydot [38;5;241m=[39m [43mG[49m[38;5;241;43m.[39;49m[43mto_dot[49m[43m([49m[43mbackend[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mpydot[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      4[0m display(SVG(G_pydot[38;5;241m.[39mcreate_svg()))

File [0;32m~/work/corneto/corneto/corneto/graph/_base.py:1058[0m, in [0;36mBaseGraph.to_dot[0;34m(self, **kwargs)[0m
[1;32m   1048[0m [38;5;250m[39m[38;5;124;03m"""Convert graph to DOT format.[39;00m
[1;32m   1049[0m 
[1;32m   1050[0m [38;5;124;03mArgs:[39;00m
[0;32m   (...)[0m
[1;32m   1054[0m [38;5;124;03m    DOT representation of the graph[39;00m
[1;32m   1055[0m [38;5;124;03m"""[39;00m
[1;32m   1056[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mcorneto[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_plotting[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m to_graphviz [38;5;28;01mas[39;00m _dot
[0;32m-> 1058[0m [38;5;28;01mreturn[39;00m [43m_dot[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/work/corneto/corneto/corneto/_plotting.py:448[0m, in [0;36mto_graphviz[0;34m(graph, graph_attr, node_attr, edge_attr, custom_edge_attr, custom_vertex_attr, edge_indexes, layout, orphan_edges, supress_warnings, backend)[0m
[1;32m    435[0m     [38;5;28;01mreturn[39;00m to_python_graphviz(
[1;32m    436[0m         graph,
[1;32m    437[0m         graph_attr,
[0;32m   (...)[0m
[1;32m    445[0m         supress_warnings,
[1;32m    446[0m     )
[1;32m    447[0m [38;5;28;01melif[39;00m backend [38;5;241m==[39m [38;5;124m"[39m[38;5;124mpydot[39m[38;5;124m"[39m:
[0;32m--> 448[0m     [38;5;28;01mreturn[39;00m [43mto_pydot[49m[43m([49m
[1;32m    449[0m [43m        [49m[43mgraph[49m[43m,[49m
[1;32m    450[0m [43m        [49m[43mgraph_attr[49m[43m,[49m
[1;32m    451[0m [43m        [49m[43mnode_attr[49m[43m,[49m
[1;32m    452[0m [43m        [49m[43medge_attr[49m[43m,[49m
[1;32m    453[0m [43m        [49m[43mcustom_edge_attr[49m[43m,[49m
[1;32m    454[0m [43m        [49m[43mcustom_vertex_attr[49m[43m,[49m
[1;32m    455[0m [43m        [49m[43medge_indexes[49m[43m,[49m
[1;32m    456[0m [43m        [49m[43mlayout[49m[43m,[49m
[1;32m    457[0m [43m        [49m[43morphan_edges[49m[43m,[49m
[1;32m    458[0m [43m    [49m[43m)[49m
[1;32m    459[0m [38;5;28;01melse[39;00m:
[1;32m    460[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mUnknown backend specified. Must be [39m[38;5;124m'[39m[38;5;124mgraphviz[39m[38;5;124m'[39m[38;5;124m or [39m[38;5;124m'[39m[38;5;124mpydot[39m[38;5;124m'[39m[38;5;124m.[39m[38;5;124m"[39m)

File [0;32m~/work/corneto/corneto/corneto/_plotting.py:351[0m, in [0;36mto_pydot[0;34m(graph, graph_attr, node_attr, edge_attr, custom_edge_attr, custom_vertex_attr, edge_indexes, layout, orphan_edges)[0m
[1;32m    340[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mto_pydot[39m(
[1;32m    341[0m     graph: BaseGraph,
[1;32m    342[0m     graph_attr: Optional[Dict[[38;5;28mstr[39m, [38;5;28mstr[39m]] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m    349[0m     orphan_edges: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mTrue[39;00m,
[1;32m    350[0m ) [38;5;241m-[39m[38;5;241m>[39m Any:
[0;32m--> 351[0m     [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpydot[39;00m
[1;32m    353[0m     is_hypergraph [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    354[0m     [38;5;28;01mif[39;00m custom_edge_attr [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

[0;31mModuleNotFoundError[0m: No module named 'pydot'

