Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from corneto.methods.carnival import milp_carnival

P = milp_carnival(G, {"I2": -1, "I1": 0}, {"T": 1}, beta_weight=0.01)
P.solve(solver="GUROBI", verbosity=1)
------------------

----- stdout -----
(CVXPY) Jan 07 08:43:10 PM: Encountered unexpected exception importing solver HIGHS:
ImportError('generic_type: type "ObjSense" is already registered!')
----- stdout -----
(CVXPY) Jan 07 08:43:10 PM: Encountered unexpected exception importing solver HIGHS:
ImportError('generic_type: type "ObjSense" is already registered!')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[14], line 4[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mcorneto[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmethods[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcarnival[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m milp_carnival
[1;32m      3[0m P [38;5;241m=[39m milp_carnival(G, {[38;5;124m"[39m[38;5;124mI2[39m[38;5;124m"[39m: [38;5;241m-[39m[38;5;241m1[39m, [38;5;124m"[39m[38;5;124mI1[39m[38;5;124m"[39m: [38;5;241m0[39m}, {[38;5;124m"[39m[38;5;124mT[39m[38;5;124m"[39m: [38;5;241m1[39m}, beta_weight[38;5;241m=[39m[38;5;241m0.01[39m)
[0;32m----> 4[0m [43mP[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43msolver[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mGUROBI[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mverbosity[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m

File [0;32m~/work/corneto/corneto/corneto/backend/_base.py:571[0m, in [0;36mProblemDef.solve[0;34m(self, solver, max_seconds, warm_start, verbosity, **options)[0m
[1;32m    569[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_backend [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    570[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mNo backend assigned.[39m[38;5;124m"[39m)
[0;32m--> 571[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_backend[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m
[1;32m    572[0m [43m    [49m[38;5;28;43mself[39;49m[43m,[49m
[1;32m    573[0m [43m    [49m[43msolver[49m[38;5;241;43m=[39;49m[43msolver[49m[43m,[49m
[1;32m    574[0m [43m    [49m[43mmax_seconds[49m[38;5;241;43m=[39;49m[43mmax_seconds[49m[43m,[49m
[1;32m    575[0m [43m    [49m[43mwarm_start[49m[38;5;241;43m=[39;49m[43mwarm_start[49m[43m,[49m
[1;32m    576[0m [43m    [49m[43mverbosity[49m[38;5;241;43m=[39;49m[43mverbosity[49m[43m,[49m
[1;32m    577[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43moptions[49m[43m,[49m
[1;32m    578[0m [43m[49m[43m)[49m

File [0;32m~/work/corneto/corneto/corneto/backend/_base.py:832[0m, in [0;36mBackend.solve[0;34m(self, p, solver, max_seconds, warm_start, verbosity, **options)[0m
[1;32m    826[0m [38;5;28;01melse[39;00m:
[1;32m    827[0m     o [38;5;241m=[39m (
[1;32m    828[0m         p[38;5;241m.[39mweights[[38;5;241m0[39m] [38;5;241m*[39m p[38;5;241m.[39mobjectives[[38;5;241m0[39m]
[1;32m    829[0m         [38;5;28;01mif[39;00m p[38;5;241m.[39mobjectives [38;5;129;01mand[39;00m p[38;5;241m.[39mweights[[38;5;241m0[39m] [38;5;241m!=[39m [38;5;241m0[39m
[1;32m    830[0m         [38;5;28;01melse[39;00m [38;5;28;01mNone[39;00m
[1;32m    831[0m     )
[0;32m--> 832[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_solve[49m[43m([49m
[1;32m    833[0m [43m    [49m[43mp[49m[43m,[49m
[1;32m    834[0m [43m    [49m[43mobjective[49m[38;5;241;43m=[39;49m[43mo[49m[43m,[49m
[1;32m    835[0m [43m    [49m[43msolver[49m[38;5;241;43m=[39;49m[43msolver[49m[43m,[49m
[1;32m    836[0m [43m    [49m[43mmax_seconds[49m[38;5;241;43m=[39;49m[43mmax_seconds[49m[43m,[49m
[1;32m    837[0m [43m    [49m[43mwarm_start[49m[38;5;241;43m=[39;49m[43mwarm_start[49m[43m,[49m
[1;32m    838[0m [43m    [49m[43mverbosity[49m[38;5;241;43m=[39;49m[43mverbosity[49m[43m,[49m
[1;32m    839[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43moptions[49m[43m,[49m
[1;32m    840[0m [43m[49m[43m)[49m

File [0;32m~/work/corneto/corneto/corneto/backend/_cvxpy_backend.py:167[0m, in [0;36mCvxpyBackend._solve[0;34m(self, p, objective, solver, max_seconds, warm_start, verbosity, **options)[0m
[1;32m    165[0m solvers [38;5;241m=[39m cp[38;5;241m.[39minstalled_solvers()
[1;32m    166[0m [38;5;28;01mif[39;00m s [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m s [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m solvers:
[0;32m--> 167[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    168[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mSolver [39m[38;5;132;01m{[39;00ms[38;5;132;01m}[39;00m[38;5;124m is not installed/supported, supported solvers are: [39m[38;5;132;01m{[39;00msolvers[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    169[0m     )
[1;32m    170[0m [38;5;66;03m# TODO: Implement parameter mapping for solvers and backends[39;00m
[1;32m    171[0m [38;5;28;01mif[39;00m max_seconds [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

[0;31mValueError[0m: Solver GUROBI is not installed/supported, supported solvers are: ['CVXOPT', 'GLPK', 'GLPK_MI', 'SCIP', 'SCIPY']

